2017/12/25 22:41:45 Error: Expected response to be successful, got 404
    at Request.handleFailure [as _handleFailure] (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-client/lib/request.js:241:11)
    at Request.<anonymous> (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-cli-util/lib/command.js:56:12)
    at concat.then (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-client/lib/request.js:135:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2017/12/25 22:41:45 {"resource":"app","id":"not_found","message":"Couldn't find that app."}
2017/12/25 22:55:31 Error: Expected response to be successful, got 404
    at Request.handleFailure [as _handleFailure] (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-client/lib/request.js:241:11)
    at Request.<anonymous> (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-cli-util/lib/command.js:56:12)
    at concat.then (/home/ubuntu/.local/share/heroku/client/node_modules/heroku-client/lib/request.js:135:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2017/12/25 22:55:31 {"resource":"app","id":"not_found","message":"Couldn't find that app."}
